// <auto-generated />
namespace DoAnCoSo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Update069 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update069));
        
        string IMigrationMetadata.Id
        {
            get { return "202306091418072_Update069"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
