// <auto-generated />
namespace DoAnCoSo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Update30051 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update30051));
        
        string IMigrationMetadata.Id
        {
            get { return "202305301250552_Update30051"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
